# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
  - stage: BuildStage
    displayName: "Stage1 - Build Blazor App"
    jobs:
      - template: templates/build.yml
  
  - stage: TestBuildJob
    displayName: "Stage2 - Test Code"
    jobs:
      - template: templates/test.yml

  - stage: DeployInfrastructure
    displayName: "Stage3 - Deploy Azure Infrastructure"
    jobs:
      - template: templates/deploy-infra.yml

  - stage: DeployAppStage
    displayName: "Stage4 - Deploy Blazor App on Azure"
    jobs:
      - template: templates/deploy-app.yml


            
