parameters:
  artifactName: ""
  buildConfiguration: ""

jobs:
  - job: BuildJob
    displayName: "Job1 - Build App and Create Artifact"
    steps:
      - checkout: self

      - task: UseDotNet@2
        displayName: "Install .NET 6 SDK"
        inputs:
            packageType: sdk
            version: "6.x"
          
      - script: |
            dotnet build -c ${{ parameters.buildConfiguration }} -o ${{ Build.ArtifactStagingDirectory }}
        displayName: "Build Solution"

      - script: |
            dotnet publish -c ${{ parameters.buildConfiguration }} -o ${{ Build.ArtifactStagingDirectory }}/publish
        displayName: "Build and Publish App"
        workingDirectory: "FSPBook.Portal"
          
      - task: PublishBuildArtifacts@1
        displayName: "Publish Artifact"
        inputs:
            pathToPublish: "${{ Build.ArtifactStagingDirectory }}/publish"
            artifactName: "${{ parameters.artifactName }}"