parameters:
  azureSubscription: ""
  resourceGroupName: ""
  location: ""
  appServicePlanName: ""
  webAppName: ""

jobs:
  - job: DeployInfraJob
    displayName: "Job3 - Deploy RG, App Service Plan and Web App"
    steps:
      - task: AzureCLI@2
        displayName: "Create Resource Group"
        inputs:
            azureSubscription: ${{ parameters.azureSubscription }}
            scriptType: 'bash'
            scriptLocation: 'inlineScript'
            inlineScript: |
              az group create --name ${{ parameters.resourceGroupName }} --location ${{ parameters.location }}

      - task: AzureCLI@2
        displayName: "Deploy Bicep"
        inputs:
            azureSubscription: ${{ parameters.azureSubscription }}
            scriptType: bash
            scriptLocation: inlineScript
            inlineScript: |
              az deployment group create \
                --resource-group ${{ parameters.resourceGroupName }} \
                --template-file infra.bicep \
                --parameters appServicePlanName=${{ parameters.appServicePlanName }} webAppName=${{ parameters.webAppName }}