parameters:
  azureSubscription: ""
  webAppName: ""
  artifactName: ""

jobs:
  - job: DeployAppJob
    displayName: 'Job4 - Deploy Blazor App on Azure'
    steps:
      - checkout: self
      - task: DownloadBuildArtifacts@1
        displayName: 'Download Artifact'
        inputs:
            artifactName: "${{ parameters.artifactName }}"
            downloadPath: "${{ Build.ArtifactStagingDirectory }}"
          
      - task: AzureWebApp@1
        displayName: "Deploy Blazor App to Web App"
        inputs:
            azureSubscription: ${{ parameters.azureSubscription }}
            appName: "${{ parameters.webAppName }}"
            package: "${{ Build.ArtifactStagingDirectory }}/${{ parameters.artifactName }}"
            appType: webApp