parameters:
  buildConfiguration: "$(buildConfiguration)"
  testResultsPath: '$(testResultsPath)'

jobs:
  - job: TestCode
    displayName: "Job2 - Run Test"
    steps:
      - script: |
            dotnet test --configuration $(buildConfiguration) --logger "trx;LogFileName=test_results.trx" --results-directory "$(testResultsPath)"
        displayName: 'Run MSTests and Generate TRX Report'
        
      - task: PublishBuildArtifacts@1
        displayName: "Publish Artifact"
        inputs:
          pathToPublish: "$(testResultsPath)"
          artifactName: "testResults"