variables:
  azureSubscription: 'vjazbasicsubscription(b192d1c3-cd31-4c42-9998-71c20e0900e6)'
  resourceGroupName: "vjazrgFSPBook"
  location: "eastus2"
  appServicePlanName: "appserviceplan-fspbook-dzaaum2rhftxw"
  webAppName: "vjazfspbookblazorapp"

jobs:
  - job: DeployInfraJob
    displayName: "Job3 - Deploy RG, App Service Plan and Web App"
    steps:
      - task: AzureCLI@2
        displayName: "Create Resource Group"
        inputs:
            azureSubscription: $(azureSubscription)
            scriptType: 'bash'
            scriptLocation: 'inlineScript'
            inlineScript: |
              az group create --name $(resourceGroupName) --location $(location)

      - task: AzureCLI@2
        displayName: "Deploy Bicep"
        inputs:
            azureSubscription: $(azureSubscription)
            scriptType: bash
            scriptLocation: inlineScript
            inlineScript: |
              az deployment group create \
                --resource-group $(resourceGroupName) \
                --template-file infra.bicep \
                --parameters appServicePlanName=$(appServicePlanName) webAppName=$(webAppName)